//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autores
    {
        public string Nombre { get; set; }
        public string Nacimiento { get; set; }
        public string Fallecimiento { get; set; }
        public string Origen { get; set; }
        public string Periodo { get; set; }
        public int IdAutor { get; set; }
        public string ImagenAutor { get; set; }
    }
}
