//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuadros
    {
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string TamañoAlto { get; set; }
        public string TamañoAncho { get; set; }
        public string Fecha_Creacion { get; set; }
        public string Estilo { get; set; }
        public int IdCuadro { get; set; }
        public string ImagenCuadro { get; set; }
    }
}
